name: car_dash
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  csv: ^5.1.1
  excel: ^2.0.4  
  charts_flutter: ^0.12.0
  fl_chart: ^0.40.0
  flutter_rating_bar: ^4.0.1
  chalk: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/csv/ILP.csv  
